# Generated by Django 5.2.4 on 2025-08-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyGSTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(help_text='Registered business name', max_length=255)),
                ('gstin', models.CharField(help_text='GST Identification Number', max_length=15)),
                ('state_code', models.CharField(help_text='State code as per GST rules', max_length=2)),
                ('address', models.TextField(help_text='Registered business address')),
                ('email', models.EmailField(blank=True, help_text='Business email for GST correspondence', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, help_text='Business contact number', max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company GST Details',
                'verbose_name_plural': 'Company GST Details',
            },
        ),
        migrations.CreateModel(
            name='GSTRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the GST rate category', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of items in this category', null=True)),
                ('hsn_code', models.CharField(blank=True, help_text='HSN code for this category', max_length=20, null=True)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=0, help_text='CGST rate in percentage (e.g., 9.00 for 9%)', max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=0, help_text='SGST rate in percentage (e.g., 9.00 for 9%)', max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=0, help_text='IGST rate in percentage (e.g., 18.00 for 18%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rate is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'GST Rate',
                'verbose_name_plural': 'GST Rates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GSTReportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B'), ('B2B', 'B2B Invoices'), ('B2C', 'B2C Invoices'), ('HSN', 'HSN Summary'), ('OTHER', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file_path', models.CharField(blank=True, max_length=255, null=True)),
                ('file_format', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_reports_generated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GST Report Log',
                'verbose_name_plural': 'GST Report Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(help_text='Date of the transaction')),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('PURCHASE', 'Purchase'), ('LOAN', 'Loan'), ('EXTENSION', 'Loan Extension'), ('RETURN', 'Return'), ('OTHER', 'Other')], default='SALE', help_text='Type of transaction', max_length=20)),
                ('invoice_number', models.CharField(help_text='Invoice or reference number', max_length=50)),
                ('party_name', models.CharField(help_text='Name of the customer/vendor', max_length=255)),
                ('party_gstin', models.CharField(blank=True, help_text='GSTIN of the customer/vendor if registered', max_length=15, null=True)),
                ('is_registered_dealer', models.BooleanField(default=False, help_text='Whether the party is a GST registered dealer')),
                ('place_of_supply', models.CharField(help_text='State code or name for GST reporting', max_length=50)),
                ('is_interstate', models.BooleanField(default=False, help_text="Whether it's an interstate transaction (IGST applicable) or intrastate (CGST+SGST)")),
                ('taxable_value', models.DecimalField(decimal_places=2, help_text='Taxable value of the transaction (before tax)', max_digits=12)),
                ('cgst_amount', models.DecimalField(decimal_places=2, default=0, help_text='CGST amount', max_digits=12)),
                ('sgst_amount', models.DecimalField(decimal_places=2, default=0, help_text='SGST amount', max_digits=12)),
                ('igst_amount', models.DecimalField(decimal_places=2, default=0, help_text='IGST amount', max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount (CGST + SGST + IGST)', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount including tax', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('gst_rate', models.ForeignKey(help_text='GST rate applied to this transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='gst.gstrate')),
            ],
            options={
                'verbose_name': 'GST Transaction',
                'verbose_name_plural': 'GST Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_date'], name='gst_gsttran_transac_86a6c1_idx'), models.Index(fields=['transaction_type'], name='gst_gsttran_transac_c66e09_idx'), models.Index(fields=['is_interstate'], name='gst_gsttran_is_inte_72b4be_idx'), models.Index(fields=['is_registered_dealer'], name='gst_gsttran_is_regi_f70d86_idx'), models.Index(fields=['content_type', 'object_id'], name='gst_gsttran_content_c91cc3_idx')],
            },
        ),
    ]
