# Generated by Django 5.2.4 on 2025-09-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companygstdetails',
            name='registration_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('COMPOSITION', 'Composition Dealer'), ('ISD', 'Input Service Distributor (ISD)'), ('TDS', 'Tax Deductor at Source (TDS)'), ('TCS', 'Tax Collector at Source (TCS)'), ('CASUAL', 'Casual Taxable Person'), ('NON_RESIDENT', 'Non-Resident Taxable Person'), ('SEZ_DEVELOPER', 'SEZ Developer'), ('SEZ_UNIT', 'SEZ Unit'), ('OIDAR', 'Online Information Database Access/Retrieval Services')], default='REGULAR', help_text='Type of GST registration', max_length=20),
        ),
    ]
