---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hinfotechnolo/FMG_ERP/
    - /bin/cp -R * $DEPLOYPATH
    - mkdir -p $DEPLOYPATH/tmp
    - touch $DEPLOYPATH/tmp/restart.txt
    - /home/hinfotechnolo/virtualenv/FMG_ERP/3.11/bin/python $DEPLOYPATH/manage.py collectstatic --noinput
    - touch $DEPLOYPATH/tmp/restart.txt
