services:
  # Web service
  - type: web
    name: pawnshop
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: RENDER
        value: true
      - key: DJANGO_SETTINGS_MODULE
        value: pawnshop_management.settings
      - key: DJANGO_ENV
        value: production
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@firstmoneygold.com
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false