# Generated by Django 5.2.1 on 2025-06-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometrics', '0002_alter_faceauthlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricsetting',
            name='lockout_duration',
            field=models.DurationField(default='00:30:00', help_text='Duration of lockout after max attempts'),
        ),
    ]
