# Generated by Django 5.2.1 on 2025-06-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the scheme', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the scheme')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate for the scheme (Yearly in %, Eg: 12%)', max_digits=5)),
                ('loan_duration', models.PositiveIntegerField(help_text='Standard loan duration in days')),
                ('minimum_amount', models.DecimalField(decimal_places=2, help_text='Minimum loan amount', max_digits=10)),
                ('maximum_amount', models.DecimalField(decimal_places=2, help_text='Maximum loan amount', max_digits=10)),
                ('additional_conditions', models.JSONField(blank=True, help_text='Additional conditions in JSON format', null=True)),
                ('start_date', models.DateField(help_text='Date when the scheme becomes active')),
                ('end_date', models.DateField(blank=True, help_text='Date when the scheme expires (leave blank for ongoing)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('upcoming', 'Upcoming'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch the scheme is associated with (leave empty for global schemes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loan_schemes', to='branches.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schemes', to='accounts.customuser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_schemes', to='accounts.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_all_schemes', 'Can view all schemes including from other branches'), ('manage_global_schemes', 'Can manage schemes that apply globally')],
                'indexes': [models.Index(fields=['status'], name='schemes_sche_status_e91afc_idx'), models.Index(fields=['start_date'], name='schemes_sche_start_d_00647a_idx'), models.Index(fields=['branch'], name='schemes_sche_branch__fee3b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SchemeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='schemes.scheme')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customuser')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
