# Generated by Django 5.2.1 on 2025-06-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='scheme',
            new_name='schemes_sch_status_739aec_idx',
            old_name='schemes_sche_status_e91afc_idx',
        ),
        migrations.RenameIndex(
            model_name='scheme',
            new_name='schemes_sch_start_d_3594f9_idx',
            old_name='schemes_sche_start_d_00647a_idx',
        ),
        migrations.RenameIndex(
            model_name='scheme',
            new_name='schemes_sch_branch__490b2f_idx',
            old_name='schemes_sche_branch__fee3b8_idx',
        ),
    ]
