# Generated by Django 5.2.3 on 2025-08-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_rename_schemes_sche_status_e91afc_idx_schemes_sch_status_739aec_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='interest_rate_structure',
            field=models.JSONField(blank=True, help_text="Dynamic interest rates based on tenure in JSON format. Example: {'0-1': 12, '1-3': 18, '3-6': 24, '6+': 36}", null=True),
        ),
    ]
