# Generated by Django 5.2.3 on 2025-08-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_organization_admin_organization_and_more'),
        ('schemes', '0003_scheme_interest_rate_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='organization',
            field=models.ForeignKey(help_text='Organization this scheme belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='accounts.organization'),
        ),
    ]
