# Generated by Django 5.2.3 on 2025-08-02 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_organization_admin_organization_and_more'),
        ('schemes', '0004_scheme_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='is_default',
            field=models.BooleanField(default=False, help_text='If true, this scheme is available to all organizations'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this scheme belongs to (null for default schemes)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='accounts.organization'),
        ),
    ]
