# Generated by Django 5.2.3 on 2025-08-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0005_scheme_is_default_alter_scheme_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='auction_on_expiry',
            field=models.BooleanField(default=False, help_text='Whether the gold will be auctioned if not redeemed by expiry'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='expiry_period',
            field=models.PositiveIntegerField(blank=True, help_text='Expiry period for gold loans in months', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='gold_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate for gold loans (Rupees per 100 Rupees per month)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='is_fixed_interest',
            field=models.BooleanField(default=False, help_text='Whether the interest rate is fixed (no additional charges)'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='is_gold_scheme',
            field=models.BooleanField(default=False, help_text='Whether this is a gold loan scheme'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='late_payment_interest',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Additional interest for late payment (Rupees per 100 Rupees per month)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='minimum_duration',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Minimum duration for gold loans in months', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='payment_due_day',
            field=models.PositiveSmallIntegerField(blank=True, default=5, help_text='Day of month when payment is due', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='special_conditions',
            field=models.TextField(blank=True, help_text='Special conditions for gold loans', null=True),
        ),
    ]
