# Generated by Django 5.2.3 on 2025-08-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0006_scheme_auction_on_expiry_scheme_expiry_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='early_period_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reduced interest rate for early repayment (Rupees per 100 Rupees per month)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='early_period_months',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Duration of early period in months (for reduced interest rate)', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='late_period_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Increased interest rate for late period (Rupees per 100 Rupees per month)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='processing_fee_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, help_text='Processing fee as percentage of loan amount', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='standard_period_months',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Duration of standard period in months (for normal interest rate)', null=True),
        ),
    ]
