# Generated by Django 5.2.8 on 2026-07-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0007_scheme_early_period_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='minimum_duration',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Minimum duration for gold loans in days', null=True),
        ),
    ]
