# Generated by Django 5.2.8 on 2026-08-28 15:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_performance_indexes'),
        ('schemes', '0008_alter_scheme_minimum_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoldRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Effective rate date')),
                ('rate_24k_per_gram', models.DecimalField(decimal_places=2, default=Decimal('7200.00'), help_text='Market price of 24K (99.9%) pure gold per gram in INR', max_digits=10)),
                ('rate_22k_per_gram', models.DecimalField(decimal_places=2, default=Decimal('6600.00'), help_text='Market price of 22K (91.6%) standard gold per gram in INR', max_digits=10)),
                ('rate_20k_per_gram', models.DecimalField(decimal_places=2, default=Decimal('6000.00'), help_text='Market price of 20K (83.3%) gold per gram in INR', max_digits=10)),
                ('rate_18k_per_gram', models.DecimalField(decimal_places=2, default=Decimal('5400.00'), help_text='Market price of 18K (75.0%) gold per gram in INR', max_digits=10)),
                ('maximum_ltv_percentage', models.DecimalField(decimal_places=2, default=Decimal('75.00'), help_text='RBI Statutory LTV Cap percentage (default 75.00%, hard ceiling 90.00%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Active rate indicator')),
                ('notes', models.CharField(blank=True, help_text='Broadcast notes / Market reason', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization for this rate (null for global standard)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold_rates', to='accounts.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_rate_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Gold Rate',
                'verbose_name_plural': 'Daily Gold Rates',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
