# Generated by Django 5.2.4 on 2025-09-06 13:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_customer_id_type'),
        ('branches', '0003_branch_organization'),
        ('transactions', '0017_sale_cgst_amount_sale_cgst_rate_sale_customer_gstin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.CharField(choices=[('gold_price', 'Gold Price'), ('interest_rate', 'Interest Rate'), ('inflation_rate', 'Inflation Rate'), ('unemployment_rate', 'Unemployment Rate'), ('gdp_growth', 'GDP Growth'), ('seasonal_factor', 'Seasonal Factor')], max_length=30)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=6, max_digits=15)),
                ('source', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Market Indicator',
                'verbose_name_plural': 'Market Indicators',
                'unique_together': {('indicator_type', 'date', 'region')},
            },
        ),
        migrations.CreateModel(
            name='RiskAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high_risk_customer', 'High Risk Customer'), ('default_prediction', 'Default Prediction'), ('cash_flow_warning', 'Cash Flow Warning'), ('unusual_pattern', 'Unusual Pattern'), ('market_volatility', 'Market Volatility')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alerts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='accounts.customer')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_alerts', to='transactions.loan')),
            ],
            options={
                'verbose_name': 'Risk Alert',
                'verbose_name_plural': 'Risk Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('very_low', 'Very Low Risk'), ('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], max_length=20)),
                ('payment_history_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_to_value_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('demographic_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('economic_indicator_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('behavioral_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_loans_count', models.IntegerField(default=0)),
                ('active_loans_count', models.IntegerField(default=0)),
                ('defaulted_loans_count', models.IntegerField(default=0)),
                ('average_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('customer_tenure_days', models.IntegerField(default=0)),
                ('last_loan_date', models.DateField(blank=True, null=True)),
                ('last_payment_date', models.DateField(blank=True, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('calculation_version', models.CharField(default='1.0', max_length=10)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='accounts.customer')),
            ],
            options={
                'verbose_name': 'Risk Profile',
                'verbose_name_plural': 'Risk Profiles',
            },
        ),
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('predicted_loan_disbursements', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('predicted_loan_repayments', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('predicted_interest_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('predicted_fee_income', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('predicted_sales_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('predicted_operating_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('predicted_net_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('seasonal_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trend_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='1.0', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_forecasts', to='branches.branch')),
            ],
            options={
                'verbose_name': 'Cash Flow Forecast',
                'verbose_name_plural': 'Cash Flow Forecasts',
                'unique_together': {('branch', 'forecast_date', 'forecast_type')},
            },
        ),
        migrations.CreateModel(
            name='LoanPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('default_risk', 'Default Risk'), ('early_repayment', 'Early Repayment'), ('extension_likelihood', 'Extension Likelihood'), ('renewal_probability', 'Renewal Probability')], max_length=30)),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('factors_considered', models.JSONField(default=dict)),
                ('model_version', models.CharField(default='1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='transactions.loan')),
            ],
            options={
                'verbose_name': 'Loan Prediction',
                'verbose_name_plural': 'Loan Predictions',
                'unique_together': {('loan', 'prediction_type')},
            },
        ),
    ]
