# Generated by Django 5.2.1 on 2025-06-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_photo',
            field=models.TextField(blank=True, help_text='Base64-encoded profile photo of customer', null=True),
        ),
    ]
