# Generated by Django 5.2.1 on 2025-06-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_customer_branch_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('management', 'Management'), ('frontline', 'Front-Line Staff'), ('support', 'Support'), ('headoffice', 'Head Office')], default='frontline', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('branch_manager', 'Branch Manager'), ('regional_manager', 'Regional Manager'), ('loan_officer', 'Loan Officer/Pawnbroker'), ('appraiser', 'Appraiser/Valuation Expert'), ('cashier', 'Cashier/Teller'), ('security', 'Security Personnel'), ('inventory_manager', 'Inventory Manager'), ('customer_service', 'Customer Service Representative'), ('it_admin', 'IT Administrator'), ('finance_manager', 'Finance/Accounting Manager'), ('compliance_officer', 'Compliance Officer')], default='cashier', max_length=30),
        ),
        migrations.AddField(
            model_name='customuser',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='managers', to='accounts.region'),
        ),
    ]
