# Generated by Django 5.2.3 on 2025-08-02 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_ensure_role_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_organization_admin',
            field=models.BooleanField(default=False, help_text='Whether user is an admin for their organization'),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Organization name', max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('plan', models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('professional', 'Professional Plan'), ('enterprise', 'Enterprise Plan')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Verification'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('contact_email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('subscription_start', models.DateTimeField(auto_now_add=True)),
                ('subscription_end', models.DateTimeField(blank=True, null=True)),
                ('max_branches', models.PositiveIntegerField(default=1)),
                ('max_users', models.PositiveIntegerField(default=3)),
                ('max_customers', models.PositiveIntegerField(default=100)),
                ('max_loans', models.PositiveIntegerField(default=100)),
                ('enable_biometrics', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization'),
        ),
    ]
