# Generated by Django 5.2.3 on 2025-08-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_organization_admin_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='auto_renew',
            field=models.BooleanField(default=True, help_text='Whether subscription should automatically renew'),
        ),
    ]
