# Generated by Django 5.2.3 on 2025-09-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_auto_renew_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhar_card', 'Aadhar Card'), ('pan_card', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('voter_id', 'Voter ID Card'), ('ration_card', 'Ration Card'), ('bank_passbook', 'Bank Passbook'), ('other', 'Other')], default='aadhar_card', help_text='Type of ID provided', max_length=50),
        ),
    ]
