# Generated by Django 5.2.3 on 2025-10-21 09:22

from django.db import migrations


def assign_customers_to_default_branch(apps, schema_editor):
    """Move customers without a branch to the default (first) branch"""
    Customer = apps.get_model('accounts', 'Customer')
    Branch = apps.get_model('branches', 'Branch')
    
    # Get the first branch as default
    default_branch = Branch.objects.first()
    
    if not default_branch:
        # If no branches exist, we can't assign customers
        print("Warning: No branches found. Customers without branches will remain unassigned.")
        return
    
    # Find customers without a branch
    customers_without_branch = Customer.objects.filter(branch__isnull=True)
    count = customers_without_branch.count()
    
    if count > 0:
        # Update all customers without a branch to use the default branch
        updated_count = customers_without_branch.update(branch=default_branch)
        print(f"Migration: Assigned {updated_count} customers without a branch to default branch '{default_branch.name}'")
    else:
        print("Migration: All customers already have a branch assigned.")


def reverse_assign_customers_to_default_branch(apps, schema_editor):
    """Reverse operation - this is not reversible, so we do nothing"""
    print("Migration: Cannot reverse customer branch assignments.")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customer_id_type'),
        ('branches', '0001_initial'),  # Ensure branches app is migrated first
    ]

    operations = [
        migrations.RunPython(
            assign_customers_to_default_branch,
            reverse_assign_customers_to_default_branch,
        ),
    ]
