# Generated by Django 5.2.4 on 2026-03-01 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20251021_0922'),
        ('branches', '0003_branch_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where this customer is registered', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='branches.branch'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.CheckConstraint(condition=models.Q(('branch__isnull', False)), name='customer_must_have_branch'),
        ),
    ]
