# Generated by Django 5.2.12 on 2026-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customer_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address_tamil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='city_tamil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name_tamil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name_tamil',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes_tamil',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_tamil',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
