# Generated by Django 5.2.9 on 2026-04-08 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_customer_address_tamil_customer_city_tamil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pawnshop_admin',
            field=models.BooleanField(default=False, help_text='Whether user is a pawnshop admin (only admin can manage staff)'),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('password_change', 'Password Change'), ('login', 'Login'), ('logout', 'Logout'), ('permission_change', 'Permission Change')], max_length=30)),
                ('model_name', models.CharField(help_text='Name of the model that was changed', max_length=100)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='ID of the changed object', null=True)),
                ('object_str', models.CharField(help_text='String representation of the changed object', max_length=500)),
                ('field_name', models.CharField(blank=True, help_text='Name of the field that was changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Old value before change', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value after change', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from where change was made', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser/User Agent information', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the change')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails_created', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_trails_target', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit trail',
                'verbose_name_plural': 'audit trails',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_au_timesta_f94d2b_idx'), models.Index(fields=['admin_user', '-timestamp'], name='accounts_au_admin_u_a793c1_idx'), models.Index(fields=['target_user', '-timestamp'], name='accounts_au_target__d44284_idx'), models.Index(fields=['change_type', '-timestamp'], name='accounts_au_change__eebcfa_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('admin_reset', 'Admin Reset'), ('forgot_password', 'Forgot Password'), ('user_change', 'User Changed')], default='admin_reset', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('changed_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_password_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'password change history',
                'verbose_name_plural': 'password change histories',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='accounts_pa_user_id_adc9e6_idx'), models.Index(fields=['changed_by_admin', '-timestamp'], name='accounts_pa_changed_ffb510_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deletion_timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role_name', models.CharField(blank=True, max_length=100)),
                ('reason_for_deletion', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('deleted_by_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_deletions_made', to=settings.AUTH_USER_MODEL)),
                ('staff_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff deletion',
                'verbose_name_plural': 'staff deletions',
                'ordering': ['-deletion_timestamp'],
                'indexes': [models.Index(fields=['deleted_by_admin', '-deletion_timestamp'], name='accounts_st_deleted_541937_idx'), models.Index(fields=['-deletion_timestamp'], name='accounts_st_deletio_9f03b9_idx')],
            },
        ),
    ]
