# Generated by Django 5.2.8 on 2026-06-14 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_is_pawnshop_admin_audittrail_and_more'),
        ('transactions', '0021_loanitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('foreclose', 'Foreclose'), ('payment', 'Payment'), ('other', 'Other')], default='update', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_edits_made', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='transactions.loan')),
            ],
            options={
                'verbose_name': 'loan edit log',
                'verbose_name_plural': 'loan edit logs',
                'ordering': ['-edited_at'],
            },
        ),
    ]
