# Generated by Django 5.2.8 on 2026-06-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_loaneditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaneditlog',
            name='changes',
            field=models.JSONField(blank=True, help_text='Field-level old/new values', null=True),
        ),
    ]
