# Generated by Django 5.2.8 on 2026-08-02 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_loaneditlog_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationVerificationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Secure, unique token for verification', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'organization verification token',
                'verbose_name_plural': 'organization verification tokens',
            },
        ),
    ]
