# Generated by Django 5.2.8 on 2026-08-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_organizationverificationtoken'),
        ('branches', '0006_alter_branchsettings_bill_header_mobile_numbers_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['branch', 'created_at'], name='customer_branch_created_idx'),
        ),
    ]
