# Generated by Django 5.2.8 on 2026-08-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank Account Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_beneficiary_name',
            field=models.CharField(blank=True, help_text='Beneficiary / Account Holder Name', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, help_text='Bank IFSC Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name', max_length=100, null=True),
        ),
    ]
