# Generated by Django 5.2.8 on 2026-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customer_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='anniversary_date',
            field=models.DateField(blank=True, help_text='Wedding / Marriage anniversary date', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth of the customer', null=True),
        ),
    ]
