# Generated by Django 5.2.8 on 2026-09-22 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_customer_anniversary_date_customer_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_credential_reset_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when portal credentials were last generated or reset', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_credential_reset_by',
            field=models.ForeignKey(blank=True, help_text='Super-Admin user who force-reset customer credentials', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credential_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='portal_active',
            field=models.BooleanField(default=True, help_text='Flag indicating whether customer has active portal access'),
        ),
        migrations.AddField(
            model_name='customer',
            name='temp_password_plain',
            field=models.CharField(blank=True, help_text='Temporary plain password/PIN for initial delivery and staff WhatsApp trigger', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Dedicated login account for customer self-service portal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='category',
            field=models.CharField(choices=[('management', 'Management'), ('frontline', 'Front-Line Staff'), ('support', 'Support'), ('headoffice', 'Head Office'), ('customer', 'Customer / Self-Service')], default='frontline', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('branch_manager', 'Branch Manager'), ('regional_manager', 'Regional Manager'), ('loan_officer', 'Loan Officer/Pawnbroker'), ('appraiser', 'Appraiser/Valuation Expert'), ('cashier', 'Cashier/Teller'), ('security', 'Security Personnel'), ('inventory_manager', 'Inventory Manager'), ('customer_service', 'Customer Service Representative'), ('it_admin', 'IT Administrator'), ('finance_manager', 'Finance/Accounting Manager'), ('compliance_officer', 'Compliance Officer'), ('customer', 'Customer (Self-Service Portal)')], default='cashier', max_length=30),
        ),
    ]
