# Generated by Django 5.2.3 on 2025-08-02 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_organization_admin_organization_and_more'),
        ('branches', '0002_branch_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='accounts.organization'),
        ),
    ]
