# Generated by Django 5.2.9 on 2026-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_branch_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsettings',
            name='bill_header_mobile_numbers',
            field=models.TextField(blank=True, help_text='Enter multiple mobile numbers separated by comma, semicolon, slash, or newline. These will be displayed in bill headers.', null=True),
        ),
    ]
