# Generated by Django 5.2.9 on 2026-06-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branchsettings_bill_header_mobile_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchsettings',
            name='personal_mobile_number',
            field=models.CharField(blank=True, help_text='Personal mobile number of branch manager or staff.', max_length=20, null=True),
        ),
    ]
