# Generated by Django 5.2.9 on 2026-06-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_branchsettings_personal_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchsettings',
            name='bill_header_mobile_numbers',
            field=models.TextField(blank=True, help_text='Enter multiple mobile numbers (40+ characters). Separated by comma, semicolon, slash, or newline. These will be displayed in bill headers.', null=True),
        ),
        migrations.AlterField(
            model_name='branchsettings',
            name='personal_mobile_number',
            field=models.CharField(blank=True, help_text='Personal mobile number of branch manager or staff (10-15 characters).', max_length=15, null=True),
        ),
    ]
