# Generated by Django 5.2.8 on 2026-08-28 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branchsettings_bill_header_mobile_numbers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashTill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Opening cash in drawer at BOD', max_digits=12)),
                ('cash_inwards', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cash receipts (repayments, fees, etc.)', max_digits=12)),
                ('cash_outwards', models.DecimalField(decimal_places=2, default=0.0, help_text='Total cash payments (disbursements, expenses, etc.)', max_digits=12)),
                ('cash_to_bank', models.DecimalField(decimal_places=2, default=0.0, help_text='Cash transferred to Bank/CIT during day', max_digits=12)),
                ('closing_balance_system', models.DecimalField(decimal_places=2, default=0.0, help_text='Computed closing balance', max_digits=12)),
                ('closing_balance_physical', models.DecimalField(blank=True, decimal_places=2, help_text='Actual physical count of notes/coins at EOD', max_digits=12, null=True)),
                ('denomination_breakdown', models.JSONField(blank=True, default=dict, help_text='Breakdown of notes (500, 200, 100, 50, 20, 10) and coins')),
                ('status', models.CharField(choices=[('open', 'Open (Active)'), ('reconciled', 'Reconciled (Pending Manager Sign-off)'), ('closed', 'Closed (Verified by Manager)'), ('mismatched', 'Discrepancy / Mismatch')], default='open', max_length=20)),
                ('discrepancy_reason', models.TextField(blank=True, help_text='Explanation if physical cash differs from system balance', null=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_tills', to='branches.branch')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_tills', to=settings.AUTH_USER_MODEL)),
                ('verified_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cash_tills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Till',
                'verbose_name_plural': 'Cash Tills',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('branch', 'cashier', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CashScrollEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('LOAN_DISBURSAL', 'Loan Disbursal (Cash)'), ('LOAN_REPAYMENT', 'Loan Repayment (Cash)'), ('BANK_DEPOSIT', 'Cash Deposit to Bank / CIT'), ('PETTY_CASH', 'Petty Cash / Office Expense'), ('ADJUSTMENT', 'Cash Adjustment / Inflow')], max_length=30)),
                ('direction', models.CharField(choices=[('IN', 'Cash In (Receipt)'), ('OUT', 'Cash Out (Payment)')], max_length=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_id', models.CharField(blank=True, help_text='Loan No, Voucher No, Receipt No, etc.', max_length=100, null=True)),
                ('description', models.TextField(help_text='Details / Narrative of the cash movement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cash_entries', to=settings.AUTH_USER_MODEL)),
                ('till', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='branches.cashtill')),
            ],
            options={
                'verbose_name': 'Cash Scroll Entry',
                'verbose_name_plural': 'Cash Scroll Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
