# Generated by Django 5.2.8 on 2026-09-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_branchcluster_branch_cluster_regionaloffice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='upi_merchant_name',
            field=models.CharField(blank=True, help_text='Merchant Name displayed on GooglePay/PhonePe/Paytm', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='upi_vpa',
            field=models.CharField(blank=True, help_text='Branch UPI Virtual Payment Address (e.g. branch@icici or business@okaxis)', max_length=100, null=True),
        ),
    ]
