# Generated by Django 5.2.1 on 2025-06-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('transactions', '0007_add_loan_last_updated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='loans',
            field=models.ManyToManyField(related_name='items', through='transactions.LoanItem', through_fields=('item', 'loan'), to='transactions.loan'),
        ),
    ]
