# Generated by Django 5.2.1 on 2025-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_loans'),
        ('transactions', '0013_merge_0012_alter_loan_scheme_add_updated_at_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='loans',
            field=models.ManyToManyField(related_name='loan_items', through='transactions.LoanItem', through_fields=('item', 'loan'), to='transactions.loan'),
        ),
    ]
