# Generated by Django 5.2.12 on 2026-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_item_tamil_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tamil_brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='tamil_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='tamil_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='tamil_tags',
            field=models.CharField(blank=True, default='', help_text='Comma-separated Tamil tags', max_length=255),
        ),
    ]
