# Generated by Django 5.2.8 on 2026-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_item_tamil_brand_item_tamil_model_item_tamil_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tamil_tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
