# Generated by Django 5.2.8 on 2026-08-11 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_performance_indexes'),
        ('branches', '0006_alter_branchsettings_bill_header_mobile_numbers_and_more'),
        ('inventory', '0006_alter_item_tamil_tags'),
        ('transactions', '0022_loan_is_first_month_interest_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('pawned', 'Pawned'), ('sold', 'Sold'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('maintenance', 'In Maintenance')], db_index=True, default='available', max_length=20),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status'], name='item_status_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['branch', 'status'], name='item_branch_status_idx'),
        ),
    ]
