# Generated by Django 5.2.8 on 2026-08-28 09:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branchsettings_bill_header_mobile_numbers_and_more'),
        ('inventory', '0007_performance_indexes'),
        ('transactions', '0027_alter_loan_is_first_month_interest_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultPouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pouch_number', models.CharField(db_index=True, help_text='Unique pouch barcode/identifier', max_length=60, unique=True)),
                ('safe_locker_number', models.CharField(db_index=True, default='Safe-01 / Locker-A1', help_text='Designated safe and locker compartment', max_length=100)),
                ('shelf_rack_number', models.CharField(blank=True, default='Rack-01 / Tray-A1', help_text='Specific rack, tray, or shelf within locker', max_length=100)),
                ('seal_barcode', models.CharField(blank=True, db_index=True, help_text='Tamper-evident security seal strip barcode number', max_length=100)),
                ('status', models.CharField(choices=[('pending_inward', 'Pending Dual Inward'), ('vaulted', 'Vaulted (Secured in Safe)'), ('in_transit', 'In Transit'), ('released', 'Released to Customer'), ('auctioned', 'Sent for Auction')], db_index=True, default='pending_inward', max_length=30)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0.0, help_text='Total gross weight in grams', max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, default=0.0, help_text='Total pure/net gold weight in grams', max_digits=10)),
                ('item_count', models.PositiveIntegerField(default=1, help_text='Total number of ornaments sealed inside')),
                ('sealed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inward_verified_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Audit and location notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vault_pouches', to='branches.branch')),
                ('custodian_checker', models.ForeignKey(blank=True, help_text='Branch Manager / Joint Keyholder who verified & locked into vault', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_pouches_verified', to=settings.AUTH_USER_MODEL)),
                ('custodian_maker', models.ForeignKey(blank=True, help_text='Staff/Appraiser who packed and sealed the pouch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_pouches_packed', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(blank=True, help_text='Associated loan for this gold pouch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vault_pouch', to='transactions.loan')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_pouches_released', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Pouch',
                'verbose_name_plural': 'Vault Pouches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('sealed', 'Pouch Sealed & Registered'), ('inward_verified', 'Dual-Custody Inward Verified'), ('location_moved', 'Relocated to New Safe/Rack'), ('audit_verified', 'Physical Audit Verified (Count & Weight Match)'), ('discrepancy', 'Audit Discrepancy Flagged'), ('released', 'Gold Released to Customer'), ('auctioned', 'Transferred to Auction Lot')], max_length=40)),
                ('old_location', models.CharField(blank=True, max_length=200)),
                ('new_location', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_audits_performed', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Joint keyholder or supervisor witness', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_audits_verified', to=settings.AUTH_USER_MODEL)),
                ('pouch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.vaultpouch')),
            ],
            options={
                'verbose_name': 'Vault Audit Log',
                'verbose_name_plural': 'Vault Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vaultpouch',
            index=models.Index(fields=['branch', 'status'], name='inventory_v_branch__57f24c_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultpouch',
            index=models.Index(fields=['safe_locker_number', 'shelf_rack_number'], name='inventory_v_safe_lo_2f0a9f_idx'),
        ),
    ]
