# Generated by Django 5.2.1 on 2025-05-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='gold_karat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purity of gold in karats', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='gross_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Total weight of the ornament in grams', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='net_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight of pure gold content in grams', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='ornament_type',
            field=models.CharField(blank=True, help_text='Type of gold ornament (e.g., Ring, Necklace, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='stone_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight of stones if any in grams', max_digits=7, null=True),
        ),
    ]
