# Generated by Django 5.2.1 on 2025-06-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_sale_customer_alter_loan_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='distribution_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
