# Generated by Django 5.2.1 on 2025-06-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_loan_distribution_amount_loan_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='customer_face_capture',
            field=models.TextField(blank=True, help_text='Base64-encoded customer photo', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='item_photos',
            field=models.TextField(blank=True, help_text='JSON string of Base64-encoded item photos', null=True),
        ),
    ]
