# Generated by Django 5.2.1 on 2025-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_loan_customer_face_capture_loan_item_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='scheme',
            field=models.CharField(choices=[('standard', 'Standard (12% - Min 3 months)'), ('flexible', 'Flexible (24% - No interest if repaid within 23 days)')], default='standard', max_length=20),
        ),
    ]
