# Generated by Django 5.2.1 on 2025-06-12 05:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_profile_photo'),
        ('branches', '0001_initial'),
        ('transactions', '0006_loan_scheme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-created_at'], 'permissions': [('can_approve_loan', 'Can approve loan'), ('can_extend_loan', 'Can extend loan'), ('can_foreclose_loan', 'Can foreclose loan')], 'verbose_name': 'loan', 'verbose_name_plural': 'loans'},
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='items',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='total_payable',
        ),
        migrations.AddField(
            model_name='loan',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='accounts.customer'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='customer_face_capture',
            field=models.ImageField(blank=True, null=True, upload_to='faces/customers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='distribution_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=12.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='item_photos',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs or base64 data'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='scheme',
            field=models.CharField(choices=[('standard', 'Standard (12% p.a.)'), ('flexible', 'Flexible (24% p.a.)')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('extended', 'Extended'), ('foreclosed', 'Foreclosed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
