# Generated by Django 5.2.1 on 2025-06-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_loan_distribution_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
