# Generated by Django 5.2.1 on 2025-06-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_payment_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='reference_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]