# Generated by Django 5.2.1 on 2025-06-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_sale_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='customer_face_capture',
            field=models.TextField(blank=True, help_text='Base64-encoded customer photo', null=True),
        ),
    ]
