# Generated by Django 5.2.1 on 2025-06-18 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_rename_schemes_sche_status_e91afc_idx_schemes_sch_status_739aec_idx_and_more'),
        ('transactions', '0011_alter_loan_customer_face_capture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='scheme',
            field=models.ForeignKey(help_text='Loan scheme applied to this loan', on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='schemes.scheme'),
        ),
    ]
