# Generated by Django 5.2.1 on 2025-06-21 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_alter_loan_scheme'),
        ('transactions', 'add_updated_at_field'),
    ]

    operations = [
    ]
