# Generated by Django 5.2.1 on 2025-06-21 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_item_loans'),
        ('schemes', '0002_rename_schemes_sche_status_e91afc_idx_schemes_sch_status_739aec_idx_and_more'),
        ('transactions', '0013_merge_0012_alter_loan_scheme_add_updated_at_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='notes',
        ),
        migrations.AddField(
            model_name='loan',
            name='items',
            field=models.ManyToManyField(through='transactions.LoanItem', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_number',
            field=models.CharField(help_text='Unique loan identifier', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='processing_fee',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='schemes.scheme'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('extended', 'Extended'), ('foreclosed', 'Foreclosed')], default='active', max_length=20),
        ),
    ]
