# Generated by Django 5.2.1 on 2025-06-21 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_loan_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='processing_fee',
            field=models.IntegerField(default=0, help_text='Processing fee amount in whole Rupees', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
