# Generated by Django 5.2.4 on 2025-08-14 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0001_initial'),
        ('transactions', '0016_alter_loan_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CGST amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='CGST rate in percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_gstin',
            field=models.CharField(blank=True, help_text="Customer's GSTIN if registered", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='gst_rate',
            field=models.ForeignKey(blank=True, help_text='GST rate applied to this sale', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='gst.gstrate'),
        ),
        migrations.AddField(
            model_name='sale',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN code for the item', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='igst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IGST amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IGST rate in percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_interstate',
            field=models.BooleanField(default=False, help_text="Whether it's an interstate sale (IGST) or intrastate (CGST+SGST)"),
        ),
        migrations.AddField(
            model_name='sale',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='State code or name for GST reporting', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SGST amount', max_digits=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SGST rate in percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total tax amount', max_digits=10),
        ),
    ]
