# Generated by Django 5.2.3 on 2025-10-18 07:49

import transactions.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_sale_cgst_amount_sale_cgst_rate_sale_customer_gstin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_document',
            field=models.FileField(blank=True, help_text='Upload loan agreement or related documents. File will be named using customer and item names.', null=True, upload_to=transactions.utils.loan_document_path),
        ),
    ]
