# Generated by Django 5.2.12 on 2026-03-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_loan_loan_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='place_of_supply_tamil',
            field=models.CharField(blank=True, help_text='Tamil place of supply', max_length=100, null=True),
        ),
    ]
