# Generated by Django 5.2.8 on 2026-03-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_create_loanitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of items'),
        ),
    ]
