# Generated by Django 5.2.8 on 2026-07-21 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_loanitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_first_month_interest_paid',
            field=models.BooleanField(default=False, help_text='Check if first month interest is paid/collected upfront', verbose_name='Is first month interest paid?'),
        ),
    ]
