# Generated by Django 5.2.8 on 2026-08-11 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_performance_indexes'),
        ('branches', '0006_alter_branchsettings_bill_header_mobile_numbers_and_more'),
        ('gst', '0002_companygstdetails_registration_type'),
        ('inventory', '0007_performance_indexes'),
        ('schemes', '0008_alter_scheme_minimum_duration'),
        ('transactions', '0022_loan_is_first_month_interest_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='issue_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('extended', 'Extended'), ('foreclosed', 'Foreclosed')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status', 'due_date'], name='loan_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['-issue_date'], name='loan_issue_date_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['branch', 'status'], name='loan_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_date'], name='sale_date_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'status'], name='sale_branch_status_idx'),
        ),
    ]
