# Generated by Django 5.2.8 on 2026-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_processing_fee_paid',
            field=models.BooleanField(default=False, help_text='Check if processing fees are paid/collected upfront', verbose_name='Is processing fees paid?'),
        ),
    ]
