# Generated by Django 5.2.8 on 2026-08-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_add_loan_is_processing_fee_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='gold_location',
            field=models.CharField(blank=True, help_text='Locker/Location where the gold is stored', max_length=255, null=True, verbose_name='Gold Location'),
        ),
        migrations.AddField(
            model_name='loan',
            name='gold_status_date',
            field=models.DateField(blank=True, help_text='Date of the status update', null=True, verbose_name='Gold Status Date'),
        ),
        migrations.AddField(
            model_name='loan',
            name='gold_status_others',
            field=models.TextField(blank=True, help_text='Any other notes or details about the gold status', null=True, verbose_name='Gold Status Others'),
        ),
        migrations.AddField(
            model_name='loan',
            name='repledge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount if repledged', max_digits=12, null=True, verbose_name='Repledge Amount'),
        ),
    ]
