# Generated by Django 5.2.8 on 2026-08-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_loan_gold_location_loan_gold_status_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='gold_status_date',
        ),
        migrations.AddField(
            model_name='loan',
            name='repledge_date',
            field=models.DateField(blank=True, help_text='Date of the repledge', null=True, verbose_name='Repledge Date'),
        ),
    ]
