# Generated by Django 5.2.8 on 2026-08-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_remove_loan_gold_status_date_loan_repledge_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_first_month_interest_paid',
            field=models.BooleanField(default=False, verbose_name='Is first month interest paid?'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='is_processing_fee_paid',
            field=models.BooleanField(default=False, verbose_name='Is processing fees paid?'),
        ),
    ]
