# Generated by Django 5.2.8 on 2026-08-28 18:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_alter_loan_is_first_month_interest_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisbursementTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque / DD')], default='CASH', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('utr_number', models.CharField(blank=True, help_text='Bank UTR / Transaction Reference', max_length=100, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Beneficiary Account Number', max_length=50, null=True)),
                ('ifsc_code', models.CharField(blank=True, help_text='Bank IFSC Code', max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, help_text='Bank Name', max_length=100, null=True)),
                ('beneficiary_name', models.CharField(blank=True, help_text='Beneficiary Name', max_length=150, null=True)),
                ('bank_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed / Success'), ('FAILED', 'Failed')], default='PROCESSED', max_length=20)),
                ('disbursed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_made', to=settings.AUTH_USER_MODEL)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_detail', to='transactions.loan')),
            ],
            options={
                'verbose_name': 'disbursement transaction',
                'verbose_name_plural': 'disbursement transactions',
                'ordering': ['-disbursed_at'],
            },
        ),
    ]
