# Generated by Django 5.2.8 on 2026-08-28 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0028_disbursementtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approval_tier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Tier 1 (Principal <= ₹2,00,000) [BM]'), (2, 'Tier 2 (Principal ₹2,00,001 - ₹10,00,000) [BM + RO]'), (3, 'Tier 3 (Principal > ₹10,00,000) [BM + RO + HO]')], db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='loan',
            name='checker_bm',
            field=models.ForeignKey(blank=True, help_text='Branch Manager who granted Tier 1 Approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved_bm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='checker_bm_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='checker_ho',
            field=models.ForeignKey(blank=True, help_text='Head Office Credit Committee who granted Tier 3 Approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved_ho', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='checker_ho_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='checker_ro',
            field=models.ForeignKey(blank=True, help_text='Regional Manager who granted Tier 2 Approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_approved_ro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='checker_ro_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='maker',
            field=models.ForeignKey(blank=True, help_text='Appraiser / Maker who initiated the loan', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='reappraisal_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved (Ready for Disbursal)'), ('rejected', 'Rejected'), ('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('extended', 'Extended'), ('foreclosed', 'Foreclosed')], db_index=True, default='active', max_length=20),
        ),
    ]
