# Generated by Django 5.2.8 on 2026-08-29 14:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('branches', '0008_branchcluster_branch_cluster_regionaloffice_and_more'),
        ('transactions', '0029_loan_approval_tier_loan_checker_bm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='accrued_interest',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cumulative daily interest accrued', max_digits=12),
        ),
        migrations.AddField(
            model_name='loan',
            name='irac_status',
            field=models.CharField(choices=[('STANDARD', 'Standard Asset (0 Overdue Days)'), ('SMA_0', 'SMA-0 (1 to 30 Overdue Days)'), ('SMA_1', 'SMA-1 (31 to 60 Overdue Days)'), ('SMA_2', 'SMA-2 (61 to 90 Overdue Days)'), ('NPA_SUBSTANDARD', 'NPA - Substandard (>90 Days Overdue)'), ('NPA_DOUBTFUL', 'NPA - Doubtful (>180 Days Overdue)'), ('NPA_LOSS', 'NPA - Loss Asset')], db_index=True, default='STANDARD', help_text='RBI IRAC Asset Classification Status', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='last_accrual_date',
            field=models.DateField(blank=True, help_text='Date of latest daily interest accrual', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='npa_date',
            field=models.DateField(blank=True, help_text='Date when loan was classified as NPA', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='overdue_days',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Number of overdue days past grace period'),
        ),
        migrations.AddField(
            model_name='loan',
            name='provisioning_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='Regulatory Loan Provisioning Percentage', max_digits=5),
        ),
        migrations.CreateModel(
            name='EODBatchExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('total_loans_processed', models.IntegerField(default=0)),
                ('total_daily_interest_accrued', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('standard_count', models.IntegerField(default=0)),
                ('sma0_count', models.IntegerField(default=0)),
                ('sma1_count', models.IntegerField(default=0)),
                ('sma2_count', models.IntegerField(default=0)),
                ('npa_count', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('logs', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eod_runs', to='branches.branch')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gl_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eod_runs', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'EOD batch execution log',
                'verbose_name_plural': 'EOD batch execution logs',
                'ordering': ['-execution_date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestAccrualLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('principal_outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('daily_interest_accrued', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cumulative_interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('irac_status', models.CharField(default='STANDARD', max_length=20)),
                ('is_posted_to_gl', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accrual_logs', to='transactions.loan')),
            ],
            options={
                'verbose_name': 'interest accrual log',
                'verbose_name_plural': 'interest accrual logs',
                'ordering': ['-date'],
                'unique_together': {('loan', 'date')},
            },
        ),
    ]
