# Generated by Django 5.2.8 on 2026-08-29 15:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0030_loan_accrued_interest_loan_irac_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanitem',
            name='released_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='released_loan_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanitem',
            name='status',
            field=models.CharField(choices=[('pledged', 'Pledged (In Custody)'), ('released', 'Partially Released'), ('redeemed', 'Fully Redeemed')], db_index=True, default='pledged', max_length=20),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_ornaments', to='transactions.loan'),
        ),
        migrations.CreateModel(
            name='PartialReleaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('release_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('previous_outstanding_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_outstanding_principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_gold_value', models.DecimalField(decimal_places=2, help_text='Market value of retained items', max_digits=12)),
                ('new_ltv_percentage', models.DecimalField(decimal_places=2, help_text='New LTV % after partial release (must be <= 75%)', max_digits=5)),
                ('customer_signature_data', models.TextField(blank=True, help_text='Base64 encoded customer signature', null=True)),
                ('witness_name', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_releases', to='transactions.loan')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partial_releases', to='transactions.payment')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_partial_releases', to=settings.AUTH_USER_MODEL)),
                ('released_items', models.ManyToManyField(related_name='partial_release_records', to='transactions.loanitem')),
            ],
            options={
                'verbose_name': 'partial release record',
                'verbose_name_plural': 'partial release records',
                'ordering': ['-release_date', '-created_at'],
            },
        ),
    ]
