# Generated by Django 5.2.8 on 2026-08-29 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0031_loanitem_released_at_loanitem_released_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanitem',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.loan'),
        ),
    ]
