# Generated by Django 5.2.8 on 2026-09-06 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_alter_loanitem_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ta', models.CharField(max_length=255)),
                ('category', models.CharField(default='Custom', max_length=100)),
                ('badge', models.CharField(default='Custom', max_length=50)),
                ('body_en', models.TextField(blank=True, default='')),
                ('body_ta', models.TextField(blank=True, default='')),
                ('is_custom', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_marketing_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Campaign Template',
                'verbose_name_plural': 'Marketing Campaign Templates',
                'ordering': ['-updated_at'],
            },
        ),
    ]
