# Generated by Django 5.2.8 on 2026-09-08 17:02

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customer_bank_account_number_and_more'),
        ('branches', '0008_branchcluster_branch_cluster_regionaloffice_and_more'),
        ('inventory', '0008_vaultpouch_vaultauditlog_and_more'),
        ('transactions', '0034_marketinglead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('purchase_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('total_gross_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total gross weight in grams', max_digits=10)),
                ('total_stone_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total stone deduction in grams', max_digits=10)),
                ('total_net_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total net weight in grams', max_digits=10)),
                ('total_payable_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Total payable net weight in grams', max_digits=10)),
                ('total_fine_gold_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='24K pure gold equivalent in grams', max_digits=10)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('melting_deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_payable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Final amount paid to customer', max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer (NEFT/RTGS/IMPS)'), ('upi', 'UPI / Digital'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Bank UTR / Cheque / Transaction ref', max_length=255, null=True)),
                ('id_proof_type', models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('passport', 'Passport'), ('other', 'Other Official ID')], default='aadhaar', max_length=30)),
                ('id_proof_number', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_purchases', to='branches.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gold_purchases', to='accounts.customer')),
                ('purchased_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_purchases_handled', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gold Purchase',
                'verbose_name_plural': 'Gold Purchases',
                'ordering': ['-purchase_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoldPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g. 22K Gold Chain, Ring, Bangles, Scrap Bar', max_length=200)),
                ('purity_karat', models.CharField(choices=[('24K', '24K (99.9% Pure Gold)'), ('22K', '22K (91.6% Standard Gold / 916 Hallmark)'), ('20K', '20K (83.3% Gold)'), ('18K', '18K (75.0% Gold)'), ('14K', '14K (58.5% Gold)'), ('scrap', 'Scrap / Mixed Gold / Melted Bar')], default='22K', max_length=10)),
                ('purity_percentage', models.DecimalField(decimal_places=2, default=Decimal('91.60'), max_digits=5)),
                ('gross_weight', models.DecimalField(decimal_places=3, help_text='Gross weight in grams', max_digits=10)),
                ('stone_weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Stone deduction in grams', max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, help_text='Net gold weight in grams', max_digits=10)),
                ('melting_loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Melting / assay loss %', max_digits=5)),
                ('payable_net_weight', models.DecimalField(decimal_places=3, help_text='Payable net weight after melting loss', max_digits=10)),
                ('rate_per_gram', models.DecimalField(decimal_places=2, help_text='Buying rate applied per gram', max_digits=10)),
                ('item_total_value', models.DecimalField(decimal_places=2, help_text='Total value for this item', max_digits=12)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_purchase_source', to='inventory.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transactions.goldpurchase')),
            ],
            options={
                'verbose_name': 'Gold Purchase Item',
                'verbose_name_plural': 'Gold Purchase Items',
            },
        ),
    ]
