# Generated by Django 5.2.8 on 2026-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_goldpurchase_goldpurchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldpurchase',
            name='customer_photo',
            field=models.TextField(blank=True, help_text='Base64-encoded customer face photo', null=True),
        ),
        migrations.AddField(
            model_name='goldpurchase',
            name='item_photos',
            field=models.TextField(blank=True, help_text='JSON array of base64 photos for gold items', null=True),
        ),
        migrations.AddField(
            model_name='goldpurchase',
            name='kyc_document',
            field=models.ImageField(blank=True, help_text='Uploaded KYC document image', null=True, upload_to='gold_purchases/kyc/'),
        ),
        migrations.AddField(
            model_name='goldpurchase',
            name='kyc_document_data',
            field=models.TextField(blank=True, help_text='Base64-encoded KYC document file data', null=True),
        ),
    ]
