# Generated by Django 5.2.8 on 2026-09-12 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0008_branchcluster_branch_cluster_regionaloffice_and_more'),
        ('transactions', '0037_marketinggroup_marketinglead_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(blank=True, default='', max_length=100)),
                ('campaign_name', models.CharField(blank=True, default='Broadcast', max_length=255)),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_phone', models.CharField(max_length=25)),
                ('recipient_type', models.CharField(default='customer', max_length=30)),
                ('channel', models.CharField(choices=[('whatsapp_web', 'WhatsApp Web (Direct Link)'), ('pywhatkit', 'PyWhatKit Auto-Blast'), ('sms', 'SMS Gateway'), ('api', 'Cloud API')], default='whatsapp_web', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('queued', 'Queued'), ('failed', 'Failed')], default='sent', max_length=30)),
                ('message_snippet', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_logs', to='branches.branch')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_logs', to='transactions.marketinggroup')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_campaign_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Campaign Log',
                'verbose_name_plural': 'Marketing Campaign Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
