# Generated by Django 5.2.8 on 2026-09-12 20:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customer_bank_account_number_and_more'),
        ('transactions', '0038_marketingcampaignlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IRACAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irac_bucket', models.CharField(choices=[('SMA_0', 'SMA-0 (1-30 Days Overdue)'), ('SMA_1', 'SMA-1 (31-60 Days Overdue)'), ('SMA_2', 'SMA-2 (61-90 Days Overdue / Pre-NPA)'), ('NPA_SUBSTANDARD', 'NPA Substandard (91-180 Days)'), ('NPA_DOUBTFUL', 'NPA Doubtful (181-365 Days)'), ('NPA_LOSS', 'NPA Loss (>365 Days / Auction Stage)')], db_index=True, max_length=30)),
                ('overdue_days', models.IntegerField(default=0)),
                ('overdue_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('channel', models.CharField(choices=[('whatsapp_web', 'WhatsApp Web'), ('pywhatkit', 'PyWhatKit Auto-Blast'), ('sms', 'SMS Gateway'), ('letter', 'Formal Letter / Notice')], default='whatsapp_web', max_length=30)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='sent', max_length=20)),
                ('message_sent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irac_alert_logs', to='accounts.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irac_alert_logs', to='transactions.loan')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_irac_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IRAC Alert Log',
                'verbose_name_plural': 'IRAC Alert Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
