# Generated by Django 5.2.8 on 2026-09-16 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_customer_bank_account_number_and_more'),
        ('transactions', '0039_iracalertlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanWhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(blank=True, default='', max_length=30)),
                ('notification_type', models.CharField(default='reminder', max_length=60)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered'), ('pending', 'Pending')], db_index=True, default='sent', max_length=20)),
                ('message_content', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('channel', models.CharField(choices=[('automated_browser', 'Playwright Automated Web'), ('pywhatkit', 'PyWhatKit Automation'), ('direct_link', 'WhatsApp Direct URL'), ('eod_cron', 'EOD Scheduled Dispatch'), ('manual', 'Manual Staff Dispatch')], default='automated_browser', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_whatsapp_logs', to='accounts.customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_logs', to='transactions.loan')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_dispatched_whatsapp_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan WhatsApp Log',
                'verbose_name_plural': 'Loan WhatsApp Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
