# Generated by Django 5.2.8 on 2026-09-16 17:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_loanwhatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutopilotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Enable 24/7 automated background execution.', verbose_name='Autopilot Master Switch')),
                ('enable_due_date_reminders', models.BooleanField(default=True, verbose_name='Due-Date Reminders')),
                ('due_reminder_days', models.CharField(default='7,3,1', help_text='Comma-separated days before due date (e.g. 7,3,1)', max_length=50)),
                ('enable_monthly_interest_reminders', models.BooleanField(default=True, verbose_name='Monthly Interest Reminders (Tiered Loans)')),
                ('enable_irac_delinquency_alerts', models.BooleanField(default=True, verbose_name='RBI IRAC Delinquency Warnings (SMA-0/1/2)')),
                ('enable_expiry_auction_notices', models.BooleanField(default=True, verbose_name='Demand & Auction Notices (NPA / 90+ Days)')),
                ('whatsapp_dispatch_time', models.TimeField(default='10:00:00', verbose_name='Daily WhatsApp Dispatch Time')),
                ('dispatch_channel', models.CharField(choices=[('headless_automated', 'Automated Headless Web'), ('pywhatkit', 'PyWhatKit Automation')], default='headless_automated', max_length=30)),
                ('enable_ltv_surveillance', models.BooleanField(default=True, verbose_name='LTV Risk Surveillance')),
                ('ltv_warning_threshold', models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=5, verbose_name='LTV Warning Threshold (%)')),
                ('ltv_critical_threshold', models.DecimalField(decimal_places=2, default=Decimal('85.00'), max_digits=5, verbose_name='LTV Critical Margin Call Threshold (%)')),
                ('ltv_check_time', models.TimeField(default='11:00:00', verbose_name='Daily LTV Check Time')),
                ('enable_repledge_retention', models.BooleanField(default=True, verbose_name='Closed Loan Re-Pledge Promos')),
                ('repledge_cooldown_days', models.IntegerField(default=30, verbose_name='Closed Loan Cooldown (Days)')),
                ('enable_birthday_greetings', models.BooleanField(default=False, verbose_name='Birthday / Festival Greetings')),
                ('marketing_dispatch_time', models.TimeField(default='15:00:00', verbose_name='Marketing Dispatch Time')),
                ('enable_owner_digest', models.BooleanField(default=True, verbose_name='Owner Nightly WhatsApp Digest')),
                ('owner_phone', models.CharField(blank=True, default='', max_length=25, verbose_name='Owner WhatsApp Phone (with Country Code)')),
                ('owner_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Owner Email (Optional)')),
                ('digest_time', models.TimeField(default='20:30:00', verbose_name='Nightly Digest Time')),
                ('safe_window_start', models.TimeField(default='09:00:00', verbose_name='Safe Window Start (TRAI)')),
                ('safe_window_end', models.TimeField(default='19:30:00', verbose_name='Safe Window End (TRAI)')),
                ('max_daily_messages', models.IntegerField(default=150, verbose_name='Max WhatsApp Messages / Day')),
                ('min_days_between_reminders', models.IntegerField(default=5, verbose_name='Anti-Spam Cooldown (Days per Loan)')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='idle', max_length=20)),
                ('last_log_summary', models.TextField(blank=True, default='')),
                ('consecutive_failures', models.IntegerField(default=0)),
                ('is_paused_by_circuit_breaker', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Autopilot Configuration',
                'verbose_name_plural': 'Autopilot Configurations',
            },
        ),
        migrations.CreateModel(
            name='AutopilotLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pillar', models.CharField(choices=[('pillar_2', 'Pillar 2: WhatsApp Collections & Reminders'), ('pillar_3', 'Pillar 3: LTV Risk Surveillance'), ('pillar_4', 'Pillar 4: Retention & Marketing'), ('pillar_5', 'Pillar 5: Owner Daily Digest'), ('system', 'System / Engine Lifecycle')], db_index=True, max_length=30)),
                ('action_name', models.CharField(max_length=100)),
                ('target_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('error_details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('skipped', 'Skipped / Out of Safe Window')], default='success', max_length=20)),
                ('executed_by', models.CharField(default='Autopilot Daemon', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Autopilot Activity Log',
                'verbose_name_plural': 'Autopilot Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
