# Generated by Django 5.2.8 on 2026-09-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_autopilotconfig_autopilotlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='autopilotconfig',
            name='enable_anniversary_greetings',
            field=models.BooleanField(default=True, verbose_name='Wedding Anniversary Greetings'),
        ),
        migrations.AlterField(
            model_name='autopilotconfig',
            name='enable_birthday_greetings',
            field=models.BooleanField(default=True, verbose_name='Birthday Greetings'),
        ),
    ]
