# Generated by Django 5.2.8 on 2026-09-20 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0042_autopilotconfig_enable_anniversary_greetings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_otp_verified',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether customer identity has been verified via OTP'),
        ),
        migrations.AddField(
            model_name='loan',
            name='otp_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='Count of invalid OTP verification attempts'),
        ),
        migrations.AddField(
            model_name='loan',
            name='otp_code',
            field=models.CharField(blank=True, help_text='6-digit OTP code sent to customer mobile for identity confirmation', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when OTP was generated', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='otp_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when customer OTP was successfully verified', null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='otp_verified_by',
            field=models.ForeignKey(blank=True, help_text='User / Officer who verified the customer OTP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans_otp_verified', to=settings.AUTH_USER_MODEL),
        ),
    ]
