# Generated by Django 5.2.8 on 2026-09-22 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0044_loan_updated_at_sync'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='loan',
                    name='updated_at',
                    field=models.DateTimeField(auto_now=True),
                ),
            ],
            database_operations=[]
        ),
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if UTR is unverified/invalid', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='utr_number',
            field=models.CharField(blank=True, db_index=True, help_text='12-digit Indian UPI / Bank transaction UTR reference number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='verified', help_text='Verification status of the payment', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when payment was verified', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Staff or Branch Manager who verified the UTR', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='gold_karat',
            field=models.DecimalField(decimal_places=2, help_text='Purity of gold in karats', max_digits=4),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='gross_weight',
            field=models.DecimalField(decimal_places=3, help_text='Total weight of the ornament in grams', max_digits=7),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='market_price_22k',
            field=models.DecimalField(decimal_places=2, help_text='Market price of 22K gold per gram at the time of loan', max_digits=10),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='net_weight',
            field=models.DecimalField(decimal_places=3, help_text='Weight of pure gold content in grams', max_digits=7),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='stone_weight',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Weight of stones if any in grams', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI QR / Digital'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI QR / Digital'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment'), ('other', 'Other')], max_length=20),
        ),
    ]
