"""Category-specific default photos for the inventory system"""

# Default photos as base64 strings for different categories
CATEGORY_PHOTOS = {
    'jewelry': """
    iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
    JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMA
    AAsTAAALEwEAmpwYAAAAB3RJTUUH5gQaDysZXrfKuwAABXtJREFUaN7tmGtsFFUUx/93Zna7W2i7pbbG
    +EAoaEUUIpo04MvEYIKpfNCIJsRCY/PBGBIKftBIeAa/+MlAYtSAihETozGa+ACJSIAItGDCw1RLQYRYb
    IFC2+3O7MydO9cPs9ty587M3N1G4wb+yc3svTt3zv93zrnnnnsXSJEiRYoUKVKk+A8hOgf/uqv8Or7ZZ0
    XNXdGU5btsItkmNGFH8YOw3rFdfOgvTyRBE7bvWUaIhcA4RA7DAU0eBkiBAnflIt6DIj4gfiQ73AbQVbr
    17EeZw8TQox5JSvUaA0MllUg0gTZkTrt+oU8awwAgDM1DF9BM0OQvA9NEra45tJi3FCeBNfXAgjkj+vMl
    """,
    
    'electronics': """
    iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
    JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMA
    AAsTAAALEwEAmpwYAAAAB3RJTUUH5gQaDysZXrfKuwAABXtJREFUaN7tmGtsFFUUx/93Zna7W2i7pbbG
    +EAoaEUUIpo04MvEYIKpfNCIJsRCY/PBGBIKftBIeAa/+MlAYtSAihETozGa+ACJSIAItGDCw1RLQYRYb
    """,
    
    'watches': """
    iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
    JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMA
    AAsTAAALEwEAmpwYAAAAB3RJTUUH5gQaDysZXrfKuwAABXtJREFUaN7tmGtsFFUUx/93Zna7W2i7pbbG
    """,
    
    'musical_instruments': """
    iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
    JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMA
    AAsTAAALEwEAmpwYAAAAB3RJTUUH5gQaDysZXrfKuwAABXtJReEFUaN7tmGtsFFUUx/93Zna7W2i7pbbG
    """,
    
    'vehicles': """
    iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
    JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMA
    AAsTAAALEwEAmpwYAAAAB3RJTUUH5gQaDysZXrfKuwAABXtJReEFUaN7tmGtsFFUUx/93Zna7W2i7pbbG
    """,
    
    'art': """
    iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
    JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMA
    AAsTAAALEwEAmpwYAAAAB3RJTUUH5gQaDysZXrfKuwAABXtJReEFUaN7tmGtsFFUUx/93Zna7W2i7pbbG
    """,
    
    'antiques': """
    iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6
    JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMA
    AAsTAAALEwEAmpwYAAAAB3RJTUUH5gQaDysZXrfKuwAABXtJReEFUaN7tmGtsFFUUx/93Zna7W2i7pbbG
    """
} 