# Generated by Django 5.2.8 on 2026-08-28 18:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0007_cashtill_cashscrollentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Standard GL Account Code e.g. 1010, 2010, 4010', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Account Title e.g. Cash in Hand, Interest Income', max_length=150)),
                ('category', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity / Capital'), ('INCOME', 'Income / Revenue'), ('EXPENSE', 'Expense')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Leave blank for Organization-Wide Standard Chart of Accounts', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_heads', to='branches.branch')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.accounthead')),
            ],
            options={
                'verbose_name': 'Account Head',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, help_text='e.g. JE-20260829-0001', max_length=50, unique=True)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('reference_type', models.CharField(choices=[('LOAN_DISBURSAL', 'Loan Disbursal'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('BANK_TRANSFER', 'Bank / CIT Remittance'), ('EXPENSE', 'Operating Expense'), ('MANUAL_ADJUSTMENT', 'Manual Journal Voucher'), ('CASH_DRAWER', 'Cash Drawer Adjustment'), ('FEE_INCOME', 'Fee / Charges Income')], db_index=True, default='MANUAL_ADJUSTMENT', max_length=30)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='Associated Loan/Payment ID or Receipt #', max_length=100)),
                ('narration', models.TextField(help_text='Description of transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='branches.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_items', to='accounting.accounthead')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Line Item',
                'verbose_name_plural': 'Journal Line Items',
            },
        ),
    ]
