# Generated by Django 5.2.8 on 2026-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='reference_type',
            field=models.CharField(choices=[('LOAN_DISBURSAL', 'Loan Disbursal'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('BANK_TRANSFER', 'Bank / CIT Remittance'), ('EXPENSE', 'Operating Expense'), ('MANUAL_ADJUSTMENT', 'Manual Journal Voucher'), ('CASH_DRAWER', 'Cash Drawer Adjustment'), ('FEE_INCOME', 'Fee / Charges Income'), ('GOLD_PURCHASE', 'Gold Purchase')], db_index=True, default='MANUAL_ADJUSTMENT', max_length=30),
        ),
    ]
